on:
  push:
    branches: [main]
  pull_request:
  workflow_call:
    secrets:
      NGROK_AUTHTOKEN:
        required: true

name: Continuous integration

jobs:
  check-secret:
    runs-on: ubuntu-latest
    outputs:
      has_authtoken: ${{ steps.check.outputs.defined }}
    steps:
      - name: Check for Secret
        id: check
        run: |
          if [ "${{ secrets.NGROK_AUTHTOKEN }}" != "" ]; then
            echo "defined=true" >> $GITHUB_OUTPUT
          else
            echo "defined=false" >> $GITHUB_OUTPUT
          fi

  udeps:
    name: Udeps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/nix-setup
      - uses: ./.github/actions/rust-cache
      - run: cargo udeps --workspace --all-targets --all-features

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/nix-setup
      - run: cargo fmt --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/nix-setup
      - uses: ./.github/actions/rust-cache
      - run: cargo clippy --all-targets --all-features --workspace -- -D warnings

  test-nix:
    name: Test Nix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/nix-setup
      - uses: ./.github/actions/rust-cache
      - run: cargo test --workspace --all-targets

  test-stable:
    name: Test Stable
    runs-on: ubuntu-latest
    needs: check-secret
    if: needs.check-secret.outputs.has_authtoken == 'true'
    steps:
      - uses: actions/checkout@v6
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      # We don't actually have sccache installed here (yet), but it still
      # benefits from the cargo cache.
      - uses: ./.github/actions/rust-cache
      - run: cargo test --features=paid-tests,long-tests --workspace --all-targets
        env:
          NGROK_AUTHTOKEN: ${{ secrets.NGROK_AUTHTOKEN }}

  test-win:
    name: Test Windows Stable
    runs-on: windows-latest
    needs: check-secret
    if: needs.check-secret.outputs.has_authtoken == 'true'
    steps:
      - uses: actions/checkout@v6
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      # We don't actually have sccache installed here (yet), but it still
      # benefits from the cargo cache.
      - uses: ./.github/actions/rust-cache
      - run: cargo test --workspace --all-tests
        env:
          NGROK_AUTHTOKEN: ${{ secrets.NGROK_AUTHTOKEN }}

  semver:
    name: Semver Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        crate: [muxado, ngrok]
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/nix-setup
      - uses: ./.github/actions/rust-cache
      - run: cargo semver-checks check-release -p ${{ matrix.crate }}
        name: semver checks

  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/nix-setup
      - uses: ./.github/actions/rust-cache
      - run: coverage-ci
      - uses: codecov/codecov-action@v6
        with:
          fail_ci_if_error: true
          files: ./lcov.info
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}


